[soc_host]
soc_manager ansible_host=<docker-host-IP> ansible_connection=ssh

[soc_host:vars]
ansible_user=<docker-host-username>
ansible_ssh_pass=<docker-host-password>
ansible_become_password=<ansible-password>
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[windows_agents]
windows_agent1 ansible_host=<windows-agent-IP>

[windows_agents:vars]
ansible_user=<windows-agent-username>
ansible_password=<windows-agent-password>
ansible_connection=winrm
ansible_winrm_transport=basic
ansible_winrm_scheme=http
ansible_winrm_port=5985
ansible_port=5985
ansible_winrm_server_cert_validation=ignore
