[soc_host]
<docker-host-IP>

[soc_host:vars]
ansible_user=<docker-host-username>
# If using password instead of SSH keys (keys are better), uncomment the line below:
ansible_ssh_pass=<docker-host-password>
