---
- name: Deploy Automated SOC Infrastructure
  hosts: soc_host
  become: yes # Run as sudo/root
  roles:
    - docker
    - wazuh
    - shuffle

- name: Deploy Windows Endpoint Agent
  hosts: windows_agents
  gather_facts: no # Speeds up execution
  roles:
    - windows_agent
