---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Docker and Dependencies
  apt:
    name:
      - ca-certificates
      - curl
      - git
      - gnupg
      - docker.io
      - docker-compose-v2 # Modern Docker Compose plugin
    state: present

- name: Ensure Docker service is running
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
